### ISSUE TITLE
CTX images are using linear position interpolation instead of hermite

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3928]
**ISIS version(s) affected**: 4.1.0 (likely 4.0) and later

**Description**  

When spiceinit'd with ISIS 4.1.0, some CTX images are using linear position interpolation instead of cubic hermite splines. This is causing errors on the order of a few meters vertically. Currently we've seen this with J03_045994_1986_XN_18N282W and J03_046060_1986_XN_18N282W so far. It is likely occurring in more images.

**How to reproduce**  

Spiceinit the cube with ISIS3 and then spiceinit the cube with ISIS4. The InstrumentPosition CacheType will be HermiteSpline under ISIS3 and Linear under ISIS4.

**Possible Solution**  

This is likely caused by the cache being significantly smaller when ALE creates it compared to ISIS.
**Additional context**

**Comment by krlberry** [comment]
This is happening with HRSC images as well, and based on where this is happening in the code, I'd expect it to happen with any LineScanner in ISIS.

**Comment by AndrewAnnex** [comment]
@jessemapel can you confirm this issue is fixed as of 4.2.0, unfortunately Ames stereo is locked to 4.1.0 at the moment

**Comment by jessemapel** [comment]
Just tested and it is still failing. Putting this on the todo list for next week :(

**Comment by jlaura** [comment]
@jessemapel Is this on the list for this week or should I pull this as a candidate for the support sprint?

**Comment by jessemapel** [comment]
@jlaura Put it in for support at this point. I don't think we'll have time to get to it this week.

**Comment by jessemapel** [comment]
Okay, confirmed this is fixed, but it just missed the 4.2 code freeze by 1 day. So, this will be out in 4.2.1 and 4.3.0
