### ISSUE TITLE
Kernel database incomplete for JunoCam data

### ISSUE THREAD

**Issue by swalterfub** [DOI-USGS/ISIS3#5765]
**ISIS version(s) affected**: 8.0.2 and 8.1.0 tested

**Description**  
When calling spiceinit, I get SPKINSUFFDATA errors on some (not all) images. The success rate is at around 40%.

**How to reproduce**  
```
junocam2isis from=JNCE_2019360_24C00001_V01.LBL to=JNCE_2019360_24C00001_V01.cub fullccd=yes
spiceinit from=JNCE_2019360_24C00001_V01_0001.cub
Group = Kernels
  NaifFrameCode             = -61500
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $juno/kernels/pck/pck00010.tpc
  TargetPosition            = ($juno/kernels/tspk/de440s.bsp,
                               $juno/kernels/tspk/juno_struct_v04.bsp)
  InstrumentPointing        = ($juno/kernels/ck/juno_sc_rec_191225_191227_v01-
                               .bc, $juno/kernels/fk/juno_v12.tf)
  Instrument                = $juno/kernels/ik/juno_junocam_v03.ti
  SpacecraftClock           = $juno/kernels/sclk/jno_sclkscet_00150.tsc
  InstrumentPosition        = $juno/kernels/spk/juno_rec_191201_200124_200129-
                              .bsp
  InstrumentAddendum        = $juno/kernels/iak/junoAddendum005.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Error                     = "An unknown NAIF error has been encountered. The
                               short explanation provided by NAIF is
                               [SPICE(SPKINSUFFDATA)]. The Naif error is
                               [Insufficient ephemeris data has been loaded to
                               compute the position of 503 (GANYMEDE) relative
                               to -61 (JUNO) at the ephemeris epoch 2019 DEC 26
                               02:11:12.589.]"
End_Group

```

**Possible Solution**  
Update the kernel database

**Additional context**

**Comment by amystamile-usgs** [comment]
I fixed an issue last week where the Juno SPK kernels were not getting picked up from NAIF. This change requires redownloading the juno kernels with the latest rclone config file. 

Grab the latest rclone by running:
`curl -LJO https://github.com/DOI-USGS/ISIS3/raw/dev/isis/config/rclone.conf`

Download Juno data with new config file by running:
`downloadIsisData juno $ISISDATA --config rclone.conf`

Let me know if this fixes your issue.

**Comment by swalterfub** [comment]
Dear Amy,
Thank you very much for your immediate help! Unfortunately, the solution does not solve the specific example. I did not go through all images again, how the success rate changes, as my example does not look too exotic.
Here is the output of my commands (I updated to ISIS 8.3 in the meantime):
```
+ spiceinit from=JNCE_2019360_24C00001_V01_0074.cub
Group = Kernels
  NaifFrameCode             = -61500
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $juno/kernels/pck/pck00010.tpc
  TargetPosition            = ($juno/kernels/tspk/de440s.bsp,
                               $juno/kernels/tspk/juno_struct_v04.bsp)
  InstrumentPointing        = ($juno/kernels/ck/juno_sc_rec_191225_191227_v01-
                               .bc, $juno/kernels/fk/juno_v12.tf)
  Instrument                = $juno/kernels/ik/juno_junocam_v03.ti
  SpacecraftClock           = $juno/kernels/sclk/jno_sclkscet_00185.tsc
  InstrumentPosition        = $juno/kernels/spk/juno_rec_191201_200124_200129-
                              .bsp
  InstrumentAddendum        = $juno/kernels/iak/junoAddendum005.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Error                     = "An unknown NAIF error has been encountered. The
                               short explanation provided by NAIF is
                               [SPICE(SPKINSUFFDATA)]. The Naif error is
                               [Insufficient ephemeris data has been loaded to
                               compute the position of 503 (GANYMEDE) relative
                               to -61 (JUNO) at the ephemeris epoch 2019 DEC 26
                               02:11:39.891.]"
End_Group
```
Best,
Sebastian

**Comment by amystamile-usgs** [comment]
For the set of images that are successfully spiceiniting, are the targets also Ganymede?

**Comment by amystamile-usgs** [comment]
I put in a possible fix. Try running: `downloadIsisData juno $ISISDATA --include="{tspk/kernels.0002.db}"` then rerunning your spiceinit call.

**Comment by swalterfub** [comment]
Thanks for your support! Still no success, though. The error message is the same, except that kernel `$juno/kernels/tspk/jup388s.bsp` is included.
Would it help if I send you the list of images which don't work?

**Comment by amystamile-usgs** [comment]
Based on the timing of these images it should be picking up jup380s.bsp. jup388s.bsp would still cause spiceinit to fail. 

I will continue working on fixing the kernels.0002.db file. In the meantime, you can specify the tspks by running:

```
spiceinit from=JNCE_2019360_24C00001_V01_0001.cub tspk="($ISISDATA/juno/kernels/tspk/de440s.bsp,$ISISDATA/juno/kernels/tspk/juno_struct_v04.bsp,$ISISDATA/juno/kernels/tspk/jup380s.bsp)"
Group = Kernels
  NaifFrameCode             = -61500
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $juno/kernels/pck/pck00010.tpc
  TargetPosition            = (/Volumes/isis_data/juno/kernels/tspk/de440s.bs-
                               p,
                               /Volumes/isis_data/juno/kernels/tspk/juno_struc-
                               t_v04.bsp,
                               /Volumes/isis_data/juno/kernels/tspk/jup380s.bs-
                               p)
  InstrumentPointing        = ($juno/kernels/ck/juno_sc_rec_191225_191227_v01-
                               .bc, $juno/kernels/fk/juno_v12.tf)
  Instrument                = $juno/kernels/ik/juno_junocam_v03.ti
  SpacecraftClock           = $juno/kernels/sclk/jno_sclkscet_00185.tsc
  InstrumentPosition        = $juno/kernels/spk/juno_rec_191201_200124_200129-
                              .bsp
  InstrumentAddendum        = $juno/kernels/iak/junoAddendum005.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Source                    = isis
End_Group
```

**Comment by amystamile-usgs** [comment]
I just update the kernel db so you can also try rerunning `downloadIsisData juno $ISISDATA --include="{tspk/kernels.0002.db}"` and try spiceiniting again.

**Comment by swalterfub** [comment]
Thank you! I can confirm that spiceinit is now picking up kernel `jup380s.bsp` and it runs through fine.

But now I get a different error while trying the next processing step, `cam2map`.
The error message is: `**PROGRAMMER ERROR** Angle cannot be a non-Null special pixel.` 
I would be very much interested what this error means as I experienced it quite often already.
Here is my full camp2map command: `cam2map from=JNCE_2019360_24C00001_V01_0001.cub map=ganymede.map lonseam=continue to=JNCE_2019360_24C00001_V01_0001.cub`
With `ganymede.map` being:
```
Group = Mapping
  ProjectionName     = Equirectangular
  CenterLongitude    = 180.0
  CenterLatitude     = 0.0
  TargetName         = GANYMEDE
  EquatorialRadius   = 2632400.0 <meters>
  PolarRadius        = 2632350.0 <meters>
  LatitudeType       = Planetocentric
  LongitudeDirection = PositiveEast
  LongitudeDomain    = 360
End_Group
End
```
For sure this time its only a user error :)

Best,
Sebastian

**Comment by amystamile-usgs** [comment]
This error typically means there is no latitude/longitude information. You can always check this by running `qview` or `campt`. Based on looking at the image in qview, it doesn't seem like there would be any surface intersection data for JNCE_2019360_24C00001_V01_0001.

**Comment by swalterfub** [comment]
Thank you so much for your quick help!
